#Updated settings at runtime
#Wed Jun 17 00:38:42 CEST 2026
energySaving=false
maxInternalTemperature=50.0
maxTemperatureRoom=30.0
pufferDeviceTemperature=20.0
targetTemperature=27.0
windowOpenThreshold=0.08
