#Updated settings at runtime
#Sat Jun 13 14:20:32 CEST 2026
energySaving=false
maxInternalTemperature=50.0
maxTemperatureRoom=30.0
pufferDeviceTemperature=20.0
targetTemperature=10.0
windowOpenThreshold=0.08
