#Updated settings at runtime
#Fri Jun 19 18:18:43 CEST 2026
energySaving=false
maxInternalTemperature=50.0
maxTemperatureRoom=30.0
pufferDeviceTemperature=20.0
targetTemperature=19.5
windowOpenThreshold=0.08
